### ISSUE TITLE
TypeError: Cannot call method 'getAttribute' of undefined

### ISSUE THREAD

**Issue by badalsharma31** [bergie/passport-saml#258]
I am trying to integrate "sample-passport-example" with okta. Showing this error on browser, while encrypting assertion in okta, and trying to decrypt using 'decryptionPvk' in code.
**Note : certificate is self genrated using oopenssl command**
```
openssl req -x509 -newkey rsa:4096 -keyout key.pem -out cert.pem -days 365 -nodes
```
 
## using following config.-

**sample-passport-example** : [https://github.com/gbraad/passport-saml-example](url)

**![Stack trace of error]**
```
TypeError: Cannot call method 'getAttribute' of undefined
   at decryptKeyInfo (/Users/badalsharma/workspace/passport-saml-example-master/node_modules/passport-saml/node_modules/xml-encryption/lib/xmlenc.js:195:52)
   at Object.decrypt (/Users/badalsharma/workspace/passport-saml-example-master/node_modules/passport-saml/node_modules/xml-encryption/lib/xmlenc.js:131:24)
   at Promise.post (/Users/badalsharma/workspace/passport-saml-example-master/node_modules/passport-saml/node_modules/q/q.js:1103:36)
   at Promise.promise.promiseDispatch (/Users/badalsharma/workspace/passport-saml-example-master/node_modules/passport-saml/node_modules/q/q.js:748:41)
   at /Users/badalsharma/workspace/passport-saml-example-master/node_modules/passport-saml/node_modules/q/q.js:1333:14
   at flush (/Users/badalsharma/workspace/passport-saml-example-master/node_modules/passport-saml/node_modules/q/q.js:110:17)
   at process._tickCallback (node.js:415:13)
```
**![Image of code_config]**
![code_config](https://user-images.githubusercontent.com/12763825/35765563-621eb89c-08ec-11e8-8eaf-6ad041ab6b28.png)

**![Image of config in 'okta']**
![config](https://user-images.githubusercontent.com/12763825/35765556-28018856-08ec-11e8-8938-51df171fc252.png)

## And working fine when okta send assertion unencrypted

**Comment by badalsharma31** [comment]
Issue resolved, As I was using older version of passport-saml. So i updated version in package.json file.
