### ISSUE TITLE
can't use MultiSamlStrategy

### ISSUE THREAD

**Issue by sibelius** [bergie/passport-saml#303]
```
Error: Cannot find module 'passport-saml/MultiSamlStrategy'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
```

**Comment by stavros-wb** [comment]
Hello @sibelius, it's a typo in the documentation. The file name is `multiSamlStrategy` so 
• either we change it to be required as `require('passport-saml/multiSamlStrategy')`
• or rename the file and `require('passport-saml/MultiSamlStrategy')`

**Comment by sibelius** [comment]
@stavros-wb this does not work because only `lib` in on npm version

I've made a PR to fix this https://github.com/bergie/passport-saml/pull/304

and let the code be more consistency
