### ISSUE TITLE
500 Cannot read property 'Status' of undefined

### ISSUE THREAD

**Issue by slider973** [bergie/passport-saml#385]
I'm using loopback-component-passport am able to successfully authenticate through their SAML connector, however when SAML.verifyLogoutResponse  I receive the following error:

TypeError
500 Cannot read property 'Status' of undefined
TypeError: Cannot read property 'Status' of undefined
    at /Users/jonathan/Documents/LVAPP/LV6/node_modules/passport-saml/lib/passport-saml/saml.js:859:41
    at Promise.apply (/Users/jonathan/Documents/LVAPP/LV6/node_modules/q/q.js:1185:26)
    at Promise.promise.promiseDispatch (/Users/jonathan/Documents/LVAPP/LV6/node_modules/q/q.js:808:41)
    at /Users/jonathan/Documents/LVAPP/LV6/node_modules/q/q.js:1411:14
    at runSingle (/Users/jonathan/Documents/LVAPP/LV6/node_modules/q/q.js:137:13)
    at flush (/Users/jonathan/Documents/LVAPP/LV6/node_modules/q/q.js:125:13)
    at process._tickCallback (internal/process/next_tick.js:61:11)

Any help would be appreciated.

**Comment by markstos** [comment]
Sorry, there's no here to provide support. You can try StackOverflow.
